version: "3.7"

services:
  frontend:
    container_name: todoapp
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
